### ISSUE TITLE
[BUG] Output have field with None and text have dict with field with text

### ISSUE THREAD

**Issue by kondera** [firattamur/llmdantic#5] opened 2024-03-21 07:56 UTC
**Description**

Hey, seems like a fun library and tried to use example that's similar to one that's in readme (would be nice to have a script/notebook to check out library). I used AzureChatOpenAI as a llm.

The result (LLMdanticResult) have field with None and result's text have dict that's filled.
text - {"rewritten": "Miód to ulubiony przysmak Kubusia Puchatka."} - Honey is Winnie the Pooh's favorite treat.
output - rewritten=None

**To Reproduce**
```python
# setup
llm = AzureChatOpenAI(
    api_key=AZURE_API_KEY,
    api_version=AZURE_API_VERSION,
    azure_endpoint=RESOURCE_ENDPOINT,
    azure_deployment=AZURE_DEPLOY,
    temperature=0,
    verbose=True,
)
class RewriteInput(BaseModel):
    text: str


class RewriteOutput(BaseModel):
    rewritten: str

    @field_validator("rewritten")
    def rewritten_text_must_be_in_polish(cls, v) -> bool:
        """ Rewritten text must be in polish language """
        ...

    @field_validator("rewritten")
    def rewritten_text_must_not_be_empty(cls, v) -> bool:
        """Rewritten text cannot be empty """
        ...

    @field_validator("rewritten")
    def rewritten_text_must_be_short(cls, v) -> bool:
        """Rewritten must be less than 100 words """
        ...

config: LLMdanticConfig = LLMdanticConfig(
    objective="Rewrite the polish text and convey the same meaning but with different phrasing and structure to ensure it is fresh and engaging.",
    inp_schema=RewriteInput,
    out_schema=RewriteOutput, 
    retry=3,
    verbose=True,
)

llmdantic = LLMdantic(llm=llm, config=config)

# polish for Winnie the Pooh likes honey
data = RewriteInput(text="Kubuś Puchatek lubi miód.")
result = llmdantic.invoke(data)
print(result.text)
# output: {"rewritten": "Miód to ulubiony przysmak Kubusia Puchatka."} - Honey is Winnie the Pooh's favorite treat.
print(result.output)
# output: rewritten=None
```

**Expected behavior**
Output should have filled fields from llm

**Comment by firattamur** [comment] 2024-03-21 08:34
Hello, 

Thank you for using the package and your kind words. The issue you're facing is related to how the validators in the RewriteOutput model class are handled.

The root cause of the problem is that the **field_validator** functions in your RewriteOutput class are **not returning the correct values**. These validator functions should **either return the value itself if it passes the validation or raise a ValueError exception if the validation fails.** However, in your code, these functions are not returning anything, resulting in None being assigned to the rewritten field.

Please let me know if you need any further assistance in resolving this issue or have additional questions. I'll be happy to provide more detailed explanations or suggest solutions.

**Comment by kondera** [comment] 2024-03-21 10:02
Oh shoot, I missed that. Thanks, after adding returns it works as intented :D

**Closed as completed** 2024-03-21 10:42 UTC
